### ISSUE TITLE
Difficulty handling required ingredient quantities.

### ISSUE THREAD

**Issue by GameDevon** [Furukia/furu-sc#1]
Items with a quantity don't seem to count as multiple items for crafting. 
- When consuming an item with any quantity, even if the recipe calls for only one, it consumes the entire stack
- Upon crafting recipes that make a large quantity of a single item, multiple separate items are created.

![crafting bug](https://github.com/Furukia/furu-sc/assets/82553545/d84f6c81-5f3a-454c-89f4-14574c9756f6)

**Comment by Furukia** [comment]
Hi. Looks like you need to setup your system quantity path setting. In DnD 5e it should look like this 
![image](https://github.com/Furukia/furu-sc/assets/67807868/2b26ce63-cd6d-4d31-9dc6-f95bceae4816)

**Comment by GameDevon** [comment]
This has now created two new issues. 
The first is that the recipe is no longer creating the output item.
The second is that it is multiplying one of the required ingredients
![crafting bug2](https://github.com/Furukia/furu-sc/assets/82553545/febf6f64-35bb-4756-911c-5e55acf6ad99)
![crafting bug3](https://github.com/Furukia/furu-sc/assets/82553545/d8ae547c-883d-402e-8492-15667c090ee9)

**Comment by Furukia** [comment]
Okay, that's confusing me.
Can you tell me your Foundry version, system and give me a .json recipe file? Also check for any error's in console. You can attach screenshot's of them here. (F12 to open the console)
If you are on v12 i wouldn't recommend using my module until an update. Foundry moved sourceId property my module relies upon. Which in turn doesn't allow to add ingredient's and so on in new world's and can introduce some unexpected behaviour in world's created on v11.

**Comment by GameDevon** [comment]
Thanks for waiting. I'm on Foundry V11 Build 315, DnD 3.0.3
[out_of_the_void.json](https://github.com/user-attachments/files/15780065/out_of_the_void.json)
