### ISSUE TITLE
Can't add two required items from the same compendium.

### ISSUE THREAD

**Issue by GameDevon** [Furukia/furu-sc#3]
Tried adding rope and arrows to the same recipe from the SRD Items compendium but whichever I add second just adds to the quantity of the first item. On V11 Build 315, DnD 5e 3.0.3.

Steps to Reproduce
- Create a new recipe
- Set recipe type to items
- Add rope and Arrows to the recipe from a compendium

Intended result:
The recipe requires rope and arrows.

Actual result
The recipe requires 2 rope.

**Comment by Furukia** [comment]
Look's like a bug to me. I'll look into this and fix it later. For now you can try working with items that are not in the compendiums.
